#!/usr/bin/env bash

if [[ ! "${TERM}" = "alacritty" ]]; then
  return
fi

if command -v tmux >/dev/null 2>&1 && [[ -z "${TMUX}" ]]; then
    if tmux list-sessions >/dev/null 2>&1; then
        tmux a
    else
        tmux new -s dev
    fi
fi
