#!/usr/bin/env bash

if ! command -v brew > /dev/null 2>&1; then
  return
fi

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

export PATH=/usr/local/bin:${PATH}

brew=/usr/local/bin/brew

function brewup() {
  $brew update
  $brew upgrade
  $brew cleanup
}
