#!/usr/bin/env bash

if ! command -v brew > /dev/null 2>&1; then
  return
fi

export PATH=/usr/local/bin:${PATH}

brew=/usr/local/bin/brew

function brewup() {
  $brew update
  $brew upgrade
  $brew cleanup
}
