#!/usr/bin/env sh

if [ `which brew 2>/dev/null | wc -l` -lt 1 ]; then
  return
fi

export PATH=/usr/local/bin:${PATH}

brew=/usr/local/bin/brew
logger=/usr/bin/logger

function brewup() {
  $brew update 2>&1 | $logger -t brewup.update
  $brew upgrade 2>&1 | $logger -t brewup.upgrade
  $brew cleanup 2>&1 | $logger -t brewup.cleanup
}
