#!/usr/bin/env bash

if ! command -v docker > /dev/null 2>&1; then
  return
fi

alias dcp='docker-compose'

docker-restart() {
  docker start $(docker ps -a -q -f status=exited -f status=created 2>/dev/null) 2>/dev/null
}
