#!/usr/bin/env bash

if [ ! -f ~/.fzf.bash ]; then
  return
fi

source ~/.fzf.bash

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"

function fzvim() {
  EDITOR=vim
  if [ ${#} -gt 0 ]
  then
      $EDITOR $*
  else
      $EDITOR $(fzf)
  fi
}
