#!/usr/bin/env bash

if [ -e "${HOME}/.fzf.bash" ]; then
  source "${HOME}/.fzf.bash"
fi

if ! command -v fzf > /dev/null 2>&1; then
  return
fi

if command -v fd > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='fd --hidden --follow --exclude .git --exclude node_modules --exclude vendor --exclude vendors'
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
fi

if command -v git > /dev/null 2>&1; then
  function gitco() {
    local branch=`git branch -vv --all | fzf --ansi --reverse`
    git checkout `echo ${branch} | awk '{print $1}' | sed 's|^remotes/origin/||'`
  }

  function gitlg() {
    git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' | fzf --ansi --reverse --tiebreak=index --no-sort --preview 'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1; }; f {}'
  }
fi

if command -v pass > /dev/null 2>&1; then
  function passfor() {
    local PASS_DIR=${PASSWORD_STORE_DIR-~/.password-store}
    local file=`find "${PASS_DIR}" -name "*.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|" | fzf --reverse -q "${1}" -1`

    if [ -n "${file}" ]; then
      pass -c "${file}"
    fi
  }

  function otpfor() {
    local PASS_DIR=${PASSWORD_STORE_DIR-~/.password-store}
    local file=`find "${PASS_DIR}" -name "*.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|" | fzf --reverse -q "${1}" -1`

    if [ -n "${file}" ]; then
      pass otp -c "${file}"
    fi
  }

  _fzf_complete_pass() {
    local PASS_DIR=${PASSWORD_STORE_DIR-~/.password-store}
    local entries=`find "$PASS_DIR" -name "*.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|"`

    _fzf_complete '--reverse' "$@" < <(
      echo "${entries}"
    )
  }

  [ -n "$BASH" ] && complete -F _fzf_complete_pass -o default -o bashdefault pass
fi
