#!/usr/bin/env bash

if [[ -e ${HOME}/.fzf.bash ]]; then
  source "${HOME}/.fzf.bash"
fi

if ! command -v fzf > /dev/null 2>&1; then
  return
fi

if command -v fd > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='fd --hidden --follow --exclude .git --exclude node_modules --exclude vendor --exclude vendors'
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
elif command -v rg > /dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND="rg --files --hidden 2> /dev/null"
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
fi

if command -v bat > /dev/null 2>&1; then
  export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {}'"
fi
