#!/usr/bin/env bash

if [[ -f ${HOME}/opt/google-cloud-sdk/path.bash.inc ]]; then
  source "${HOME}/opt/google-cloud-sdk/path.bash.inc"
fi

if [[ -f ${HOME}/opt/google-cloud-sdk/completion.bash.inc ]]; then
  source "${HOME}/opt/google-cloud-sdk/completion.bash.inc"
fi

if ! command -v gcloud > /dev/null 2>&1; then
  return
fi

export BOTO_CONFIG=/dev/null
export CLOUDSDK_PYTHON=/usr/bin/python

gcloud_auth() {
  rm -rf "/tmp/${USER}*"
  gcloud auth login --no-launch-browser

  gcloud config unset compute/region
  gcloud config set project "$(gcloud projects list | grep dev | awk '{print $1}')"

  if command -v docker > /dev/null 2>&1; then
    gcloud --quiet auth configure-docker "eu.gcr.io"
  fi
}
