#!/usr/bin/env bash

if command -v eza >/dev/null 2>&1; then
  alias ls='eza --group-directories-first'
  alias ll='eza -la --git --group-directories-first --time-style=relative'
  alias l='eza -la --git'
  t() { eza --tree --level="${1:-3}" --ignore-glob=".git|node_modules" "${@:2}"; }
else
  if [ `uname` == "Darwin" ]; then
    export CLICOLOR=1
    export LS_OPTIONS=''
    export LSCOLORS=GxFxCxDxBxegedabagaced
  else
    export LS_OPTIONS='--color=auto'
  fi

  alias ls='ls $LS_OPTIONS'
  alias ll='ls -trhAl'
  alias l='ls -la'

  t() {
    tree -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst --filelimit 30 -L ${1:-3} -aC $2
  }
fi
