#!/usr/bin/env sh

if [ `uname` == 'Darwin' ]; then
  export CLICOLOR=1
  export LS_OPTIONS=''
  export LSCOLORS=GxFxCxDxBxegedabagaced
else
  export LS_OPTIONS='--color=auto'
fi

alias ls='ls $LS_OPTIONS'
alias ll='ls -trhAl'
alias l='ls -la'


function t() {
    # Defaults to 3 levels deep, do more with `t 5` or `t 1`
    # pass additional args after
    tree -I '.git|node_modules|bower_components|.DS_Store' --dirsfirst --filelimit 30 -L ${1:-3} -aC $2
}
