#!/usr/bin/env bash

if ! command -v node > /dev/null 2>&1; then
  return
fi

export PATH=${HOME}/.npm_packages/bin:${PATH}

alias npmi="npm install --no-save"
alias npmb="npm run build"
alias npmw="npm run build:watch"
alias npms="npm run start"
alias npmt="npm run test"
alias npmq="npm run quality"
