#!/usr/bin/env bash

if [ `uname` != "Darwin" ]; then
  return
fi

function os_clean() {
  directory=${1:-`pwd`}

  echo "Cleaning .DS_Store and ._* files in $directory and subdirectories ..."
  find $directory -name ".DS_Store" -exec rm -f {} \;
  find $directory -name "._*" -exec rm -f {} \;
}
