#!/usr/bin/env bash

function addPass() {
  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local RESET='\033[0m'

  if ! command -v pass 1>/dev/null 2>&1; then
    echo -e "${RED}pass not found, aborting${RESET}"
    return 1
  fi

  if [ "${#}" -eq 0 ]; then
    echo -e "${RED}Usage addPass [folder]/[name] (e.g. addPass commons/wifi)${RESET}"
    return 1
  fi

  echo -e "${GREEN}Updating password store${RESET}"
  echo
  pass git pull

  echo -e "${GREEN}Importing public keys of team${RESET}"
  echo
  ls ~/.password-store/.public_keys/*.gpg | xargs gpg --import
  cat ~/.password-store/.public_keys/gpg.conf >> ~/.gnupg/gpg.conf

  echo -e "${GREEN}Adding password, don't forget to run command 'pass git push' when ended${RESET}"
  echo
  pass insert -m "${@}"
}
