[colors.bright]
black = "0x676767"
blue = "0x6871ff"
cyan = "0x79e7fa"
green = "0x43d326"
magenta = "0xff76ff"
red = "0xf8291c"
white = "0xfffefe"
yellow = "0xf1cf00"

[colors.cursor]
cursor = "0xf0cb09"
text = "0x122637"

[colors.normal]
black = "0x000000"
blue = "0x1477da"
cyan = "0x00c5c7"
green = "0x3cdf2b"
magenta = "0xff2b6f"
red = "0xff2600"
white = "0xc7c7c7"
yellow = "0xffe600"

[colors.primary]
background = "0x173347"
foreground = "0xffffff"

[font]
size = 12.0

[selection]
save_to_clipboard = true

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
