window:
  startup_mode: Maximized
  decorations: none
  padding:
    x: 5
    y: 5

font:
  size: 12.0

alt_send_esc: false

selection:
  save_to_clipboard: true

shell:
  program: /usr/local/bin/bash
  args:
    - --login

colors:
  primary:
    background: '0x173347'
    foreground: '0xffffff'

  cursor:
    text: '0x122637'
    cursor: '0xf0cb09'

  normal:
    black:   '0x000000'
    red:     '0xff2600'
    green:   '0x3cdf2b'
    yellow:  '0xffe600'
    blue:    '0x1477da'
    magenta: '0xff2b6f'
    cyan:    '0x00c5c7'
    white:   '0xc7c7c7'

  bright:
    black:   '0x676767'
    red:     '0xf8291c'
    green:   '0x43d326'
    yellow:  '0xf1cf00'
    blue:    '0x6871ff'
    magenta: '0xff76ff'
    cyan:    '0x79e7fa'
    white:   '0xfffefe'
