#!/usr/bin/env bash

set -o nounset -o pipefail

install() {
  local DOTFILES_HOSTNAME
  DOTFILES_HOSTNAME="$(hostname)"

  cat \
    <(curl -q -sS -L "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts") \
    <(curl -q -sS -L "https://someonewhocares.org/hosts/zero/hosts") \
    <(echo "127.0.0.1 ${DOTFILES_HOSTNAME}") |
    grep -E -v '^$' |
    grep -E -v '^\s*#' |
    grep -E '^(0.0.0.0|127.0.0.1|255.255.255.255|::1|fe00::|ff02::)' |
    tr -s '[:blank:]' ' ' |
    sort |
    uniq |
    grep -v "ɢ" |
    sudo tee /etc/hosts >/dev/null
}
