#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
    cd "$(dirname "${FILE_SOURCE}")" && pwd
  )
  fi
}

clean() {
  if command -v orbctl >/dev/null 2>&1; then
    orbctl reset -y
  fi

  sudo rm -rf "${HOME}/.docker"
}

install() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    packages_install_desktop "orbstack"
    if command -v orbctl >/dev/null 2>&1; then
      orbctl completion bash >"$(script_dir)/../sources/orbctl-completion"
    fi
  fi

  packages_install ctop
}
