#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.python_history"
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  packages_install python

  if command -v brew >/dev/null 2>&1; then
    brew unlink "python" && brew link "python"
  fi

  if ! command -v python >/dev/null 2>&1; then
    return
  fi

  mkdir -p "${HOME}/opt/python"

  python3 -m venv "${HOME}/opt/python/venv"

  source "${SCRIPT_DIR}/../sources/_01_first"
  source "${SCRIPT_DIR}/../sources/_06_python"

  if ! command -v pip >/dev/null 2>&1; then
    return
  fi

  pip install --upgrade pip
}
