#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

install() {
  local SCRIPT_DIR="$(script_dir)"

  if command -v brew >/dev/null 2>&1; then
    packages_install go-task

    if command -v task >/dev/null 2>&1; then
      task --completion=bash >"${SCRIPT_DIR}/../sources/task-completion"
    fi
  fi
}
