#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local TELEPRESENCE_VERSION="2.3.0"

  local OS
  OS="$(uname -s | tr "[:upper:]" "[:lower:]")"
  local ARCH
  ARCH="$(uname -m | tr "[:upper:]" "[:lower:]")"

  if [[ ${ARCH} == "x86_64" ]]; then
    ARCH="amd64"
  elif [[ ${ARCH} =~ ^armv.l$ ]]; then
    ARCH="arm"
  fi

  curl -q -sSL --max-time 300 -o "${HOME}/opt/bin/telepresence" "https://app.getambassador.io/download/tel2/${OS}/${ARCH}/${TELEPRESENCE_VERSION}/telepresence"
  chmod +x "${HOME}/opt/bin/telepresence"
}
