#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  if command -v brew >/dev/null 2>&1; then
    packages_install_desktop visual-studio-code
  fi

  if [[ -d "${HOME:?}/Library/Application Support/Code/User" ]] && [[ -f "${SCRIPT_DIR}/../vscode/keybindings.json" ]]; then
    cp "${SCRIPT_DIR}/../vscode/keybindings.json" "${HOME:?}/Library/Application Support/Code/User/keybindings.json"
  fi

  if command -v code >/dev/null 2>&1; then
    local EXTENSIONS=(
      "alefragnani.project-manager"
      "artdiniz.quitcontrol-vscode"
      "cmstead.jsrefactor"
      "dbaeumer.vscode-eslint"
      "donjayamanne.githistory"
      "EditorConfig.EditorConfig"
      "esbenp.prettier-vscode"
      "foxundermoon.shell-format"
      "golang.go"
      "ms-azuretools.vscode-docker"
      "MS-CEINTL.vscode-language-pack-fr"
      "pflannery.vscode-versionlens"
      "PKief.material-icon-theme"
      "streetsidesoftware.code-spell-checker"
      "stylelint.vscode-stylelint"
      "syler.sass-indented"
      "waderyan.gitblame"
      "wesbos.theme-cobalt2"
    )

    for extension in ${EXTENSIONS[@]}; do
      code --install-extension "${extension}" --force
    done
  fi
}
