#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  if command -v brew >/dev/null 2>&1; then
    brew install --cask visual-studio-code
  fi

  if [[ -f "${HOME:?}/Library/Application Support/Code/User/keybindings.json" ]] && [[ -f "${SCRIPT_DIR}/../vscode/keybindings.json" ]]; then
    cp "${SCRIPT_DIR}/../vscode/keybindings.json" "${HOME:?}/Library/Application Support/Code/User/keybindings.json"
  fi

  if command -v code >/dev/null 2>&1; then
    local EXTENSIONS=(
      "aaron-bond.better-comments"
      "abusaidm.html-snippets"
      "alefragnani.project-manager"
      "artdiniz.quitcontrol-vscode"
      "cmstead.jsrefactor"
      "CoenraadS.bracket-pair-colorizer"
      "dbaeumer.vscode-eslint"
      "donjayamanne.githistory"
      "EditorConfig.EditorConfig"
      "EQuimper.react-native-react-redux"
      "esbenp.prettier-vscode"
      "formulahendry.auto-close-tag"
      "formulahendry.auto-rename-tag"
      "foxundermoon.shell-format"
      "golang.go"
      "hashicorp.terraform"
      "oouo-diogo-perdigao.docthis"
      "mikestead.dotenv"
      "mrmlnc.vscode-scss"
      "ms-azuretools.vscode-docker"
      "ms-python.python"
      "PKief.material-icon-theme"
      "samuelcolvin.jinjahtml"
      "secanis.jenkinsfile-support"
      "Shelex.vscode-cy-helper"
      "stylelint.vscode-stylelint"
      "streetsidesoftware.code-spell-checker"
      "waderyan.gitblame"
      "wesbos.theme-cobalt2"
    )

    for extension in ${EXTENSIONS[@]}; do
      code --install-extension "${extension}" --force
    done
  fi
}
